config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true,
                      length: { minimum: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    @title = 'About Us'
    @content = 'This is the "about" page.'
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)

    if (@post.save)
      redirect_to @post
    else
      render 'new'
    end

  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTutorial</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <a class="navbar-brand" href="#">Rails Tutorial</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item mx-4">
            <%= link_to "Home", home_path %>
          </li>
          <li class="nav-item mx-4">
            <%= link_to "Create post", new_post_path %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container my-4">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p>
  <%= @content %>
</p>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>

  <h3>
    <%= post.title %>
  </h3>

  <p>
    <%= post.body %>
  </p>

<% end %>

app/views/posts/new.html.erb
<h1>Add post</h1>
<%= form_for :post, url: posts_path do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |message| %>
      <div class="alert alert-danger">
        <%= message %>
      </div>
    <% end %>
  <% end %>

  <p>
      <%= f.label :title %><br>
      <%= f.text_field(:title, { :class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, { :class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({ :class => 'btn btn-primary' }) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<p>
  <%= @post.body %>
</p>